# This is a basic workflow to help you get started with Actions
name: CI
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql2
        ports: ['3306:3306']
